apiVersion: v2
name: sonarr
description: A Helm chart for Sonarr
home: https://github.com/linuxserver/docker-sonarr

maintainers:
- name: mtomwing
  email: mtomwing@gmail.com
  url: https://paperback.dev

type: application
version: 1.0.0
appVersion: 2.0.0.5343-ls119
