apiVersion: v1
kind: Service
metadata:
  name: {{ include "synclounge.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synclounge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-web
      port: 8088
      targetPort: http-web
      protocol: TCP
    - name: http-server
      port: 8089
      targetPort: http-server
      protocol: TCP
  selector:
    {{- include "synclounge.selectorLabels" . | nindent 4 }}
