{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.hostPath }}
{{- if not .Values.persistence.claimName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "valheim-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
{{- end }}
{{- end }}