apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: valheim-1
    port: {{ .Values.valheim.server.basePort }}
    targetPort: valheim-1
    protocol: UDP
  - name: valheim-2
    port: {{ .Values.valheim.server.basePort | add 1 }}
    targetPort: valheim-2
    protocol: UDP
  - name: valheim-3
    port: {{ .Values.valheim.server.basePort | add 2 }}
    targetPort: valheim-3
    protocol: UDP
  selector:
    {{- include "valheim-server.selectorLabels" . | nindent 4 }}
