replicaCount: 1

image:
  repository: lloesche/valheim-server
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  annotations: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

valheim:
  server: 
    name: My Awesome Valheim Server
    password: hunter2
    public: false
    basePort: 2456
    updateIntervalSeconds: 10800  # 3hrs
    timezone: Etc/UTC
    restartCron: "0 * * * *"
    updateCron: "*/15 * * * *"
  world:
    name: myworld
    backupIntervalSeconds: 10800  # 3hrs
    backupMaxAgeDays: 3

persistence:
  enabled: false
  size: 1Gi
  hostPath: ""
  claimName: ""
  storageClassName: ""